export { default as AdminTabs } from "./adminTabs";
export { default as MakeAddModal } from "./MakeAddModal";
export { default as BaseFileUploader } from "./BaseFileUploader";
export { default as DeleteConfirmationModal } from "./DeleteModal";
export { default as MakeEditIModal } from "./MakeEditIModal";
export { default as ActiveConfirmationModal } from "./ActiveConfirmationModal";
export { default as FeatureConfirmationModal } from "./FeatureConfirmationModal";
export { default as MakeDetailModal } from "./MakeDetailModal";
export { default as MarqueeDetails } from "./MarqueeDetails";
